spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/ps_db
    username: postgres
    password: temp
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
  jpa:
    open-in-view: false
    #    hibernate:
    #      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
    show-sql: true

kafka:
  signup-topic: signup_service_persist_service_topic
  reply-topic: reply_persist_service_signup_service_topic
  reply-group: persist_service_group
  bootstrap-servers: localhost:9092
  enable-autocommit: false
  auto-offset-reset: latest
  isolation-level: read_committed