version: '3'

services:
  postgres:
    image: postgres:11.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=temp
      - POSTGRES_DB=ps_db
      - TZ=Europe/Kiev
    ports:
      - 5432:5432

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      MAX_MSG_BYTES: '10000000'
      TZ: Europe/Kiev
      KAFKA_CREATE_TOPICS_SEPARATOR: ","
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  signup-service:
    image: 'signup-service:0.0.1-SNAPSHOT'
    ports:
      - 8081:8081
    restart: on-failure
    environment:
      - SERVER_PORT=8081
      - TZ=Europe/Kiev
    depends_on:
      - kafka
      - postgres

  persistence-service:
    image: 'persistence-service:0.0.1-SNAPSHOT'
    ports:
      - 8082:8082
    restart: on-failure
    environment:
      - SERVER_PORT=8082
      - TZ=Europe/Kiev
    depends_on:
      - kafka
      - postgres